### ISSUE TITLE
Add sync dispatch option to FleurContext

### ISSUE THREAD

**Issue by petamoriken** [fleur-js/fleur#241]
When used `requestAnimationFrame` in the View, e.g. game development with react-pixi, state of the Store changes with delay of a frame. Add to an option to change the status to `Operation#dispatch` immediately.

```ts
context.dispatch(identifier, payload, { asap: true });
```

This option should be ignored in SSR.

---

Alternative:

```ts
interface DispatchOptions {
  /** default: "animationFrame" */
  clientSideQueue: null | "microTask" | "task" | "animationFrame";
}
```

FYI: [RxJS Scheduler types](https://github.com/ReactiveX/rxjs/blob/bf65ea3545d36b9beac591fbf57285f50cb27228/docs_app/content/guide/scheduler.md#scheduler-types)

**Comment by hanakla** [comment]
Thanks for open issue!

I understand the need for a synchronous `dispatch`.

However, I don't think it's wise to add a synchronization option for `dispatch`. This is because it exposes the Operation layer to how the Action is processed by the View and gives room for timing-dependent complexity.

A better idea for using Fleur for react-pixi-fiber, in my opinion, is to specify how dispatch is handled in FleurContext. This is because it allows for consistent processing of Actions within the application.

Ex.
```tsx
<FleurContext value={context} options={{
  batchedUpdate: (cb) => cb,
  synchronousDispatch: true,
}} />
```

If you need a synchronization option on a per-dispatch basis, I'd like to hear why.

**Comment by petamoriken** [comment]
@hanakla Nice idea! It will solve my problem.
